[package]
name = "genetic_algo"
version = "0.1.0"
authors = ["P-Shreyas-Shetty <ps2shreyas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"
rand = "0.8.5"
